import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useState} from 'react';

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [counter, setCounter] = useState(4);
    //useState(0) indicates counter starting point
    const handleClick = () => {
      setCounter(counter + 1);
    };
    const minusClick = () => {
      setCounter(counter - 1);
    };
  return (
    <>
      <Head>
        <title>Florentine pizza</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Link href={"/"}>Back to home</Link>
          <h2 className="recipePageTitle">
           Florentine pizza
          </h2>
          <img src="https://realfood.tesco.com/media/images/Florentine-pizza-LGH-2cc73fa2-bc01-4120-8dbd-c364556b499b-0-1400x919.jpg"/>
          <h4 className="numServings">Currently feeds {counter}</h4>
          <button onClick={handleClick} className="servings">Add serving</button>
          <button onClick={minusClick} className="servings">Minus serving</button>
          <h3 className="ingredList">Ingredients:</h3>
          <ul className="ingpage1">
            <li>{100 * counter}g tin chopped tomatoes</li>
            <li>{60 * counter}g baby spinach, wilted</li>
            <li>{31.25 * counter}g ({1 * counter}oz) mozzarella ball, torn</li>
            <li>{62.5 * counter}g bag grated mozzarella</li>
            <li>{22 * counter}g pack Parma ham, torn</li>
            <li>{1 * counter} eggs</li>
            <li>{125 * counter}g ({0.25 * counter}lb) strong bread flour</li>
            <li>{0.25 * counter} tsp caster sugar</li>
            <li>{3.5 * counter}g dried yeast</li>
            <li>{0.5 * counter} tbsp extra-virgin olive oil, plus extra for greasing</li>
          </ul>
          <h3 className="ingredList">Recipe:</h3>
          <ul className="ingpage1">
            <li>To make the pizza dough, mix the flour, sugar, {0.5 * counter} tsp salt, and yeast in a bowl. Stir in the oil and add about {75 * counter}ml lukewarm water to make a soft, but not sticky dough.
            </li>
            <li>Tip onto a floured work surface and knead for 10 mins. Transfer to a clean bowl, cover with oiled clingfilm and set aside to prove in a warm place for 1 hr, or until doubled in size.
            </li>
            <li>Meanwhile, cook the tomatoes in a pan until thickened and reduced; season well. Preheat the oven to its highest setting. Divide the dough into {counter} and shape each into a ball. Roll out thinly and put on 4 baking sheets lined with nonstick baking paper.
            </li>
            <li>Spread each base with tomato sauce, then scatter over the spinach, mozzarella and ham. Bake, in batches if needed, for 8 mins.
            </li>
            <li>Crack an egg in the centre of each pizza. Continue baking for 2-3 mins more, until the egg is just set and the crust is crisp.
            </li>
          </ul>
          <div className= "recipeCont">
                <Link href="/page1"> <h6>Creamy vegan mushroom pasta </h6></Link>{" "}
              <Link href="/page1">
                {" "}
                <img className="recipeImageBottom" src="https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/vegan_mushroom_pasta_28266_16x9.jpg" />
            </Link>
            </div>
        </div>
      </main>
    </>
  );
}
