import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div>
          <Link href={"/"}>Back to home</Link>
          <h1 className="h1page1">Page 2</h1>
          <h2 className="h2page1">Faith will add a recipe here!</h2>
          <h3 className="h3page1">Ingredients:</h3>
          <ul className="ingpage1">
            <li></li>
          </ul>
          <h4>Recipe:</h4>
          <ul>
            <li></li>
          </ul>
        </div>
      </main>
    </>
  );
}
